sonar.projectKey=Note-app
sonar.projectName=Note app
sonar.host.url=http://localhost:9000

sonar.sources=frontend/src,backend/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.ico

sonar.sourceEncoding=UTF-8