sonar.projectKey=nest-js-note-api-10pearls
sonar.projectName=nest-js-note-api-10pearls

sonar.sources=src

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
sonar.javascript.lcov.reportPaths=../coverage/lcov.info
sonar.test.inclusions=**/*.spec.ts

sonar.sourceEncoding=UTF-8 